### ISSUE TITLE
Contribute this to upstream

### ISSUE THREAD

**Issue by satya164** [frostney/react-native-create-library#1]
It'll be great to improve the `react-native create-library` the command. Any plans to contribute this to upstream?

**Comment by frostney** [comment]
I would love that and this is definitely something I want to do, but I'm not sure if it's stable enough for that just yet.
The reason this is a separate repository is mostly because I wanted a "safe" space to experiment with some ideas and I wasn't sure if my approach might be too opinionated.

**Comment by esutton** [comment]
It would be helpful the generated project included a few example ReactMethods and simple implementations in Java, Objective-C, and Windows.

This would really help developers get going quickly and result in many new native modules being built:

**My Wish List:**
- A ReactMethod **version** function that just returns a version string "1.2.3" or something.
- A ReactMethod **add** math function that takes a ReadableMap as an input.

Input:
{
   a: 4,
   b: 2
 }

and returns a map

Output:
{
  a: 4,
  b: 2,
  result: 6
}
- A ReactMethod demonstrating use of a callback
- A ReactMethod demonstrating use of a Promise
- An index.js to expose the example ReactMethod's to JS.
- An /example/ app with a react-native project that uses all example ReactMethod's

Thank you for sharing your work!

I spent nearly 2-weeks just getting an Android native module and example project going by copying various patterns used by react-native-fs and others.  This tools will be a great help.

I may start all over using your tool since creating the iOS project could waste another week!
